### ISSUE TITLE
Document tests

### ISSUE THREAD

**Issue by meator** [crazy-complete/crazy-complete#16]
How should I run tests on crazy-complete? The `test/` subdirectory contains several executables (`crazy-complete-test`, `test.py`, `test.sh`, `test_conversion.sh`, `test_error_messages/test_error_messages.py`). Should I run all of them to run the full testsuite?

Several tests are marked as `failed` in `test.py`. No error/warning message is printed, other tests continue to run and the Python script exits with a nonzero exit status. Are the tests up to date?

**Comment by braph** [comment]
Hello Meator!

I cleaned up the tests folder a bit. Now, there are several `run.{sh,py}` scripts in the subdirectories, and a `run.sh` in the test directory to run them all. (`crazy-complete-test` is not a test, it's a definition file for the tests)

The tests are up to date and pass for me. The `tests/run.py` script goes through all the tests described in `tests.yaml` and generates a new file `tests.new.yaml`, which then can be diffed (or be used as the new `tests.yaml` if the output is right).

If some of the tests don't pass for you (which I'm surprised of), you can attach the `tests.new.yaml` file. I hope that this is sufficient to fix the failed tests.

**Comment by meator** [comment]
Here's my test output: [stdout.txt](https://github.com/user-attachments/files/17612191/stdout.txt) + [stderr.txt](https://github.com/user-attachments/files/17612192/stderr.txt) (I can give you a merged log if you want it). There are 61 failures marked in it. I have found no `tests.new.yaml` file (maybe some of the failures prevented the creation of this file).

**Comment by braph** [comment]
Did you look inside the `tests` directory? The `tests.new.yaml` should be there. I am pretty sure that the problem isn't in the completion files but rather at a higher level. The only silly example I can think of is that you don't have `bash-completions` installed. Do you have the `/usr/share/bash-completion` directory? If you do, I am pretty clueless what else could be wrong... (maybe I should check for the presence of all shells, the presence of `tmux` and the presence of `/usr/share/bash-completion` before running the tests...)

**Comment by meator** [comment]
It is possible that I am lacking some dependencies. I have the `bash-completion` and `tmux` packages installed.

I didn't find the `tests.new.yaml` because my file search utility respects `.gitignore`. I have looked again and found it: [tests.new.yaml](https://github.com/user-attachments/files/17616199/tests.new.yaml.txt)

**Comment by braph** [comment]
Hello Meator,

no, you don't lack any dependencies.

The problem was that I didn't know about `~/.inputrc` when I created the tests. I knew that I must not read the user's RC files when spawning the shells, but I didn't know bash reads this file (which, for me, was customized).

The `.inputrc` defines how the `readline` library handles user input. 

The corresponding lines that caused the problems were:
```
set show-all-if-ambiguous on
set show-all-if-unmodified on
```

These lines caused that, on my machine, there was only one tab press needed when completing amiguous arguments.
On other machines there are two tab presses needed.

I fixed the tests by including these two lines in the bash startup code.

I also added a check if all necessary programs are installed.

Please tell me if that fixes the tests for you.

**Comment by meator** [comment]
Tests still fail. [stdout.txt](https://github.com/user-attachments/files/17621930/stdout.txt) + [stderr.txt](https://github.com/user-attachments/files/17621934/stderr.txt); [tests.new.yaml](https://github.com/user-attachments/files/17621943/tests.new.yaml.txt)

**Comment by braph** [comment]
Thanks for your fast response. The tests fail, because the ordering of the options is different. The completion files themselves are working. It's just that the output has the wrong order.

**sigh** I have no clue how to handle this, maybe I also have to set the locale (but actually I cannot imagine that this is the problem, since the output is all ASCII).

Another approach would be to write a little domain specific language for the tests and parse the output of the completion.

Instead of matching the whole output string and having test-specifications like this:
```
bash_expected: |
  > crazy-complete-test test -
  --arg=                           --special-chars-in-description=
  --exclusive-1                    -A
  --exclusive-2                    -F
  --flag                           -O
  --help                           -arg=
  --optional=                      -flag
  --repeatable-arg=                -h
  --repeatable-flag                -optional=
```

I could write:
```
bash_expected: |
has_option(--arg=)
has_option(--exclusive=)
not_has_option(...)
```

I guess this is the best solution, since the ordering of options may change with the shell's versions... However this would take some time.

**Comment by braph** [comment]
Hello Meator,

I updated the code for spawning the shells. Now the `LC_*` variables are set to `C`. I also disabled the history for `bash` by passing `+o history` to the command.

The tests are working on Arch Linux, Debian and Fedora. I hope that they work for you as well!

**Comment by meator** [comment]
I can confirm that tests no longer fail on my computer.

I have wondered how you can reliably test shell completions. I have briefly read through the code and it looks like `tmux` is used to interact with the three shells. Can this interfere with local tmux sessions? Why have you chosen tmux? Have alternative programs such as [expect](https://en.wikipedia.org/wiki/Expect) been considered?

I'm kinda curious about your thought process, because I consider this to be a nontrivial problem. I myself don't really know how I would test interactive programs.

**Comment by braph** [comment]
Hi Meator,

thanks for your reply.

> Can this interfere with local tmux sessions?

Well, each session is named with a prefix `crazy-complete-test-`, so there shouldn't occur any problems.

> Why have you chosen tmux?

Because that was the first thing that came in to my mind that seemed doable.

> Have alternative programs such as [expect](https://en.wikipedia.org/wiki/Expect) been considered?

No. But I have considered emulating a terminal using pythons `pty` module. I wrote a first script that works so far (I'll attach it if you are interested)

[term.txt](https://github.com/user-attachments/files/17637268/term.txt)

**Comment by braph** [comment]
Hello Meator!

I implemented another method for running the tests using two thrird-party modules named `pyte` and `pexpect` (My first approach of running the tests only using python's builtin `pty` module failed, because it didn't handle terminal escape sequences).

The script `test/tests/run.py` now takes an optional parameter `--driver={pyte|tmux}` for specifying which method to use, with `pyte` as default.

This isn’t the final version of the testing setup. The current code misses an error handling in case `crazy-complete` fails to create the scripts. And, with the new method of testing, I can implement a more aggressive form of parallelizing to make the tests run faster.

I’ll change the remaining code at a later time.
